Education/Education.Web/Models/AlumnosModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Education.Web.Models
{
    public class AlumnosModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}

Education/Education.Web/Controllers/AlumnosController.cs
using Education.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Web.Controllers
{
    public class AlumnosController : Controller
    {
        // GET: Alumnos
        public ActionResult Index()
        {
            var alumnosBL = new AlumnosBL();
            var ListaAlumnos = alumnosBL.ObtenerAlumnos();
            return View(ListaAlumnos);
        }
    }
}

Education/Education.Web/Controllers/DocenteController.cs
using Education.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Web.Controllers
{
    public class DocenteController : Controller
    {
        // GET: Docente
        public ActionResult Index()
        {
            var docenteBL = new DocenteBL();
            var listadeDocente = docenteBL.ObtenerDocente();
            return View(listadeDocente);
        }
    }
}

Education/Education.Web/Controllers/GradoController.cs

using Education.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Web.Controllers
{
    public class GradoController : Controller
    {
        // GET: Grado
        public ActionResult Index()
        {
            var gradoBL = new GradoBL();
            var ListaGrado = gradoBL.ObtenerGrado();
            return View(ListaGrado);
        }
    }
}

Education/Education.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Education/Education.Web/Controllers/ModalidadController.cs
using Education.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Web.Controllers
{
    public class ModalidadController : Controller
    {
        // GET: Modalidad
        public ActionResult Index()
        {
            var modalidadBL = new ModalidadBL();
            var ListaModalidad = modalidadBL.ObtenerModalidad();
            return View(ListaModalidad);
        }
    }
}

Education/Education.Web/Views/Alumnos/Index.cshtml
@model List<Education.BL.Alumnos>
@{
    ViewBag.Title = "Index";
}

<h2>Alumnos</h2>


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Nombre
            </th>
            <th>
                Seccion
            </th>
        </tr>
    </thead>
@foreach (var alumnos in Model)
{
    <tr>
        <td>@alumnos.Id</td>
        <td>@alumnos.Nombre</td>
        <td>@alumnos.Seccion</td>
    </tr>
}

</table>


Education/Education.Web/Views/Docente/Index.cshtml
@model List<Education.BL.Docente>
@{
    ViewBag.Title = "Index";
}

<h2>Docente</h2>


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            
            <th>
                Id
            </th>
            <th>
                Nombre
            </th>
            <th>
                Area
            </th>


        </tr>
    </thead>
    @foreach (var Docente in Model)
    {
        <tr>
            <td>@Docente.Id</td>
            <td>@Docente.Nombre</td>
            <td>@Docente.Area</td>
        </tr>

    }

</table>



Education/Education.Web/Views/Grado/Index.cshtml
@model List<Education.BL.Grado>
@{
    ViewBag.Title = "Index";
}

<h2>Grados</h2>


<table class="table table-bordered table-hover">
    <thead>
        <tr>

            <th>
                Id
            </th>
            <th>
                Grados
            </th>


        </tr>
    </thead>
    @foreach (var Grado in Model)
    {
        <tr>
            <td>@Grado.Id</td>
            <td>@Grado.Grados</td>
            
        </tr>

    }

</table>



Education/Education.Web/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<center>
    <h2>Instituto No Gubernamental Departamental Tecnologico Las Vegas</h2>
    <h2>Light & Vision School and Institute</h2>
</center>

Education/Education.Web/Views/Modalidad/Index.cshtml
@model List<Education.BL.Modalidad>
@{
    ViewBag.Title = "Index";
}

<h2>Modalidad</h2>


<table class="table table-bordered table-hover">
    <thead>
        <tr>

            <th>
                Id
            </th>
            <th>
                Nombre
            </th>
        </tr>
    </thead>
    @foreach (var Modalidad in Model)
    {
        <tr>
            <td>@Modalidad.Id</td>
            <td>@Modalidad.Modalidades</td>
           
        </tr>

    }

</table>





Education/Education.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Education Records", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Lista de Alumnos", "Index", "Alumnos")
                    </li>

                    <li>
                        @Html.ActionLink("Docentes", "Index", "Docente")
                    </li>

                    <li>
                        @Html.ActionLink("Grados", "Index", "Grado")
                    </li>
                    <li>
                        @Html.ActionLink("Modalidades", "Index", "Modalidad")
                    </li>

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>